Implement vaccination sites
zinza-academy/covid-19-vaccine-portal-nestjs-thanghq24 pull request #19
Opened 2023-06-26 08:11 UTC by thanghq24

2023-06-27 02:42 UTC, hungnp194 requested changes

2023-06-27 02:42 UTC, hungnp194 commented on src/vaccination-sites/vaccination-sites.controller.ts
> +    @Query('address', new DefaultValuePipe(null)) address: string,
Viết query vào dto, convert type dùng Type của class-transformer cho gọn

2023-06-27 02:42 UTC, hungnp194 commented on src/vaccination-sites/vaccination-sites.service.ts
> +    address: string,
từ 3 args trở lên thì truyền bằng object cho gọn, hoặc tận dụng từ dto class

2023-06-28 04:31 UTC, hungnp-zinza approved these changes

2023-06-28 04:31 UTC, merged