Implement documents
zinza-academy/covid-19-vaccine-portal-nestjs-thanghq24 pull request #22
Opened 2023-07-05 04:31 UTC by thanghq24

2023-07-05 07:10 UTC, hungnp194 approved these changes

2023-07-05 07:10 UTC, hungnp194 commented on src/documents/documents.controller.ts
> +
check mimetype của file chứ nhỉ?

2023-07-05 07:10 UTC, hungnp194 commented on src/documents/documents.controller.ts
> +    console.log('controller: ', file);
bỏ console.log

2023-07-05 07:10 UTC, hungnp194 commented on src/documents/documents.service.ts
> +  }
remove file

2023-07-05 07:10 UTC, hungnp194 commented on src/documents/documents.controller.ts
> +  }
download file phải có thêm header các kiểu chứ nhỉ.
Ví dụ như Content-disposition?

2023-07-05 07:11 UTC, hungnp194 requested changes
Feedback

2023-07-05 07:17 UTC, thanghq24 commented on src/documents/documents.controller.ts
> +
theo doc của Nestjs thì mime type có thể bị spoof nên họ đề xuất check bằng magic number của file ạ

2023-07-10 10:42 UTC, hungnp194 approved these changes

2023-07-10 10:43 UTC, merged